version: "3.7"
services:
  app:
    container_name: ayon-app
    restart: always
    image: ayon
    ports:
      - "80:3001"
    links:
      - mongo
  mongo:
    container_name: ayon-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ayon_data:/server/data/db:rw
  
  reminder:
    container_name: ayon-reminder
    image: reminder
    ports:
      - "8082:8082"
    links:
      - app

  prometheus:
    image: prom/prometheus:0.18.0
    volumes:
        - ./statistics/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'
  node-exporter:
      image: prom/node-exporter:v0.18.1
      ports:
        - '9100:9100'
  grafana:
        image: grafana/grafana:3.0.0-beta7
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=pass
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
volumes:
  ayon_data:
