version: "3.7"
services:
  app:
    container_name: ayon-app
    restart: always
    image: claudiapreda2307/ayon:latest
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: ayon-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ayon_data:/server/data/db:rw
volumes:
  ayon_data:
