version: "3.7"
services:
  app:
    container_name: ayon-app
    restart: always
    image: claudiapreda2307/ayon:latest
    ports:
      - "80:3001"
    links:
      - mongo
    networks:
      - backend
  mongo:
    container_name: ayon-mongo
    networks:
      - backend
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ayon_data:/server/data/db:rw
  
  reminder:
    container_name: ayon-reminder
    image: claudiapreda2307/ayon:reminder
    ports:
      - "8082:8082"
    links:
      - app
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
        - ./statistics/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'
    networks:
        - backend
  node-exporter:
      image: prom/node-exporter:latest
      ports:
        - '9100:9100'
      networks:
        - backend
  # grafana:
  #       image: grafana/grafana:3.0.0-beta7
  #       environment:
  #           - GF_SECURITY_ADMIN_PASSWORD=pass
  #       depends_on:
  #           - prometheus
  #       ports:
  #           - "3000:3000"
volumes:
  ayon_data:
networks:
    backend:
