version: "3.7"
services:
  app:
    restart: always
    image: claudiapreda2307/ayon-server:latest
    ports:
      - "80:3001"
    links:
      - mongo
    networks:
      - backend
    deploy:
      replicas: 1

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ayon_data:/server/data/db:rw
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  
  reminder:
    image: claudiapreda2307/ayon-reminder:latest
    restart: always
    ports:
      - "8082:8082"
    links:
      - app
    networks:
      - backend
    deploy:
      replicas: 1
    
  client:
    image: claudiapreda2307/ayon-client:latest
    restart: always
    ports:
      - "5002:5002"
    links:
      - app
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2
    stdin_open: true
    tty: true

  prometheus:
    image: prom/prometheus:latest
    volumes:
        - ./statistics/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'
    networks:
        - backend
    deploy:
      replicas: 1

  node-exporter:
      image: prom/node-exporter:latest
      ports:
        - '9100:9100'
      networks:
        - backend
      deploy:
        replicas: 1

volumes:
  ayon_data:
networks:
    backend:
    frontend:
