global:
    scrape_interval: 10s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets:
              - 'localhost:9090'
    - job_name: 'app_backend'
      static_configs:
          - targets:
              - 'app:3001'
    - job_name: 'app_reminder'
      static_configs:
          - targets:
              - 'reminder:8082'
    - job_name: 'node_exporter'
      static_configs:
          - targets:
              - 'node-exporter:9100'
