// 📧 Send notify email

POST /api/notify/ HTTP/1.1
Host: localhost:8082
Content-Type: application/json
cache-control: no-cache

{
    "email": "predoiumihai@gmail.com",
    "plan": [
    {
        "title": "Workout",
        "details": "Wake-up and start working out.",
        "location": "Home",
        "time": "12:00"
    }
  ]
}
